// src/App.tsx
import React, { useState, useEffect } from 'react';
import { Header } from './components/Header';
import { MetricsOverview } from './components/MetricsOverview';
import { DataOverviewStats } from './components/DataOverviewStats';
import { QuickShortcuts } from './components/QuickShortcuts';
import { GlobalSearchModal } from './components/GlobalSearchModal';
import { AlertDetailModal } from './components/AlertDetailModal';
import { TodoDetailModal } from './components/TodoDetailModal';
import { ShortcutConfigModal } from './components/ShortcutConfigModal';
import { QuickActionModal } from './components/QuickActionModal';
import { SubsystemModuleView } from './components/SubsystemModuleView';

import {
  PrimaryModule,
  PlatformMetrics,
  AlertItem,
  TodoItem,
  ShortcutItem,
} from './types';
import {
  INITIAL_METRICS,
  INITIAL_ALERTS,
  INITIAL_TODOS,
  INITIAL_SHORTCUTS,
} from './data/mockData';
import { CheckCircle2, AlertCircle } from 'lucide-react';

export default function App() {
  // Navigation state
  const [activeModule, setActiveModule] = useState<PrimaryModule>('home');
  const [activeSubMenuId, setActiveSubMenuId] = useState<string | undefined>(undefined);
  const [currentSpace, setCurrentSpace] = useState<string>('prod_default');

  // Core Data States
  const [metrics, setMetrics] = useState<PlatformMetrics>(INITIAL_METRICS);
  const [alerts, setAlerts] = useState<AlertItem[]>(INITIAL_ALERTS);
  const [todos, setTodos] = useState<TodoItem[]>(INITIAL_TODOS);
  const [shortcuts, setShortcuts] = useState<ShortcutItem[]>(() => {
    try {
      const saved = localStorage.getItem('datacraft_shortcuts_v2');
      if (saved) {
        const parsed = JSON.parse(saved);
        if (Array.isArray(parsed) && parsed.length > 0) {
          return parsed.map((item: ShortcutItem) => {
            const { badge, ...rest } = item;
            return rest;
          });
        }
      }
    } catch (e) {
      console.error(e);
    }
    return INITIAL_SHORTCUTS;
  });

  // Modal states
  const [isSearchOpen, setIsSearchOpen] = useState(false);
  const [selectedAlert, setSelectedAlert] = useState<AlertItem | null>(null);
  const [selectedTodo, setSelectedTodo] = useState<TodoItem | null>(null);
  const [isShortcutConfigOpen, setIsShortcutConfigOpen] = useState(false);
  const [quickActionKey, setQuickActionKey] = useState<string | null>(null);

  // Toast Notification state
  const [toastMessage, setToastMessage] = useState<string | null>(null);
  const [toastType, setToastType] = useState<'success' | 'info' | 'warning'>('success');

  const showToast = (msg: string, type: 'success' | 'info' | 'warning' = 'success') => {
    setToastMessage(msg);
    setToastType(type);
    setTimeout(() => {
      setToastMessage(null);
    }, 3200);
  };

  // Keyboard shortcut: Cmd/Ctrl + K for Global Search
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.key === 'k') {
        e.preventDefault();
        setIsSearchOpen((prev) => !prev);
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, []);

  // Alert Handlers
  const handleResolveAlert = (alertId: string) => {
    setAlerts((prev) =>
      prev.map((a) =>
        a.id === alertId ? { ...a, status: 'resolved' as const } : a
      )
    );
    showToast('告警已成功处置并自动触发重跑自愈链路！');
  };

  const handleIgnoreAlert = (alertId: string) => {
    setAlerts((prev) =>
      prev.map((a) =>
        a.id === alertId ? { ...a, status: 'ignored' as const } : a
      )
    );
    showToast('该告警已加入静默观察白名单', 'info');
  };

  // Todo Handlers
  const handleApproveTodo = (id: string) => {
    setTodos((prev) =>
      prev.map((t) => (t.id === id ? { ...t, status: 'approved' as const } : t))
    );
    showToast('审批已同意通过，权限/模型变更已自动下发生效！');
  };

  const handleRejectTodo = (id: string) => {
    setTodos((prev) =>
      prev.map((t) => (t.id === id ? { ...t, status: 'rejected' as const } : t))
    );
    showToast('审批工单已驳回并通知申请人重新提交', 'info');
  };

  // Shortcut Save / Reset Handlers
  const handleSaveShortcuts = (updated: ShortcutItem[]) => {
    setShortcuts(updated);
    try {
      localStorage.setItem('datacraft_shortcuts_v2', JSON.stringify(updated));
    } catch (e) {
      console.error(e);
    }
    showToast('快捷入口配置已成功保存并实时生效！');
  };

  const handleResetDefaultShortcuts = () => {
    setShortcuts(INITIAL_SHORTCUTS);
    try {
      localStorage.removeItem('datacraft_shortcuts_v2');
    } catch (e) {
      console.error(e);
    }
    showToast('已成功恢复系统预设快捷入口');
  };

  // Trigger Action from Shortcut
  const handleTriggerShortcut = (actionKey: string, module?: PrimaryModule, subMenuId?: string) => {
    // If it is one of the interactive action modals
    if (['create_sync_job', 'open_sql_ide', 'apply_table_perm', 'diagnose_job'].includes(actionKey)) {
      setQuickActionKey(actionKey);
      return;
    }

    // Direct navigation to target module & secondary menu
    if (module && module !== 'home') {
      setActiveModule(module);
      if (subMenuId) {
        setActiveSubMenuId(subMenuId);
      }
      return;
    }

    if (actionKey) {
      setQuickActionKey(actionKey);
    }
  };

  return (
    <div className="min-h-screen bg-[#F2F3F5] text-slate-800 font-sans antialiased flex flex-col selection:bg-[#FF6A00] selection:text-white">
      {/* 1. Global Header with integrated 1st-level Navigation */}
      <Header
        activeModule={activeModule}
        onSelectModule={(mod, subId) => {
          setActiveModule(mod);
          setActiveSubMenuId(subId);
        }}
        activeSubMenuId={activeSubMenuId}
        pendingTodos={todos}
        alerts={alerts}
        onOpenTodos={() => {
          setSelectedTodo(todos.find((t) => t.status === 'pending') || todos[0] || null);
        }}
        onOpenAlerts={() => {
          setSelectedAlert(alerts.find((a) => a.status === 'active') || alerts[0] || null);
        }}
        onNavigateHome={() => {
          setActiveModule('home');
          setActiveSubMenuId(undefined);
        }}
      />

      {/* 2. Main Workspace Area */}
      <main className="flex-1 max-w-[1600px] w-full mx-auto p-3.5 sm:p-5">
        {activeModule === 'home' ? (
          <div className="space-y-3.5">
            {/* 3.1 Platform Core Metrics Overview - Top 4 Cards */}
            <section id="workbench-metrics-overview">
              <MetricsOverview
                metrics={metrics}
                onFilterAlerts={(sev) => {
                  setSelectedAlert(alerts.find((a) => a.severity === sev) || alerts[0] || null);
                }}
                onNavigateDevelopment={() => {
                  setActiveModule('development');
                }}
                onNavigateScheduling={() => {
                  setActiveModule('scheduling');
                }}
                onNavigateQuality={() => {
                  setActiveModule('governance');
                }}
              />
            </section>

            {/* 3.2 Data Overview Statistics (数据总览统计: 数据源, 数据表, 字段, 数据量) */}
            <section id="workbench-data-overview-section">
              <DataOverviewStats
                onShowToast={showToast}
                onSelectDimension={(key) => {
                  if (key === 'table') {
                    setActiveModule('metadata');
                  } else if (key === 'datasource') {
                    setActiveModule('ingestion');
                  }
                }}
              />
            </section>

            {/* 3.3 Quick Shortcuts Bar */}
            <section id="workbench-shortcuts-section" className="pt-2 sm:pt-2.5">
              <QuickShortcuts
                shortcuts={shortcuts}
                onTriggerAction={handleTriggerShortcut}
                onOpenConfigModal={() => setIsShortcutConfigOpen(true)}
              />
            </section>
          </div>
        ) : (
          /* Subsystem Dedicated Module Workspace */
          <SubsystemModuleView
            module={activeModule}
            activeSubMenuId={activeSubMenuId}
            onNavigateHome={() => {
              setActiveModule('home');
              setActiveSubMenuId(undefined);
            }}
            onOpenQuickAction={handleTriggerShortcut}
            onShowToast={showToast}
          />
        )}
      </main>

      {/* 4. Global Modals */}
      {/* 4.1 Global Search Modal (Cmd+K) */}
      <GlobalSearchModal
        isOpen={isSearchOpen}
        onClose={() => setIsSearchOpen(false)}
        onSelectItem={(item) => {
          showToast(`已定位资产：【${item.title}】(${item.type})`);
        }}
      />

      {/* 4.2 Alert RCA Detail Modal */}
      <AlertDetailModal
        alert={selectedAlert}
        onClose={() => setSelectedAlert(null)}
        onResolve={handleResolveAlert}
      />

      {/* 4.3 Todo Approval Detail Modal */}
      <TodoDetailModal
        todo={selectedTodo}
        onClose={() => setSelectedTodo(null)}
        onApprove={handleApproveTodo}
        onReject={handleRejectTodo}
      />

      {/* 4.4 Customize Shortcuts Config Modal */}
      <ShortcutConfigModal
        isOpen={isShortcutConfigOpen}
        onClose={() => setIsShortcutConfigOpen(false)}
        shortcuts={shortcuts}
        onSaveShortcuts={handleSaveShortcuts}
        onResetDefault={handleResetDefaultShortcuts}
      />

      {/* 4.5 Quick Action / SQL IDE / Sync / Perm Modal */}
      <QuickActionModal
        actionKey={quickActionKey}
        onClose={() => setQuickActionKey(null)}
        onSuccessToast={showToast}
      />

      {/* 5. Toast Feedback */}
      {toastMessage && (
        <div className="fixed bottom-6 right-6 z-50 animate-in fade-in slide-in-from-bottom-5 duration-200">
          <div
            className={`px-4 py-2.5 rounded-lg shadow-xl flex items-center gap-2.5 text-xs font-medium border bg-white ${
              toastType === 'success'
                ? 'border-emerald-200 text-slate-800'
                : 'border-orange-200 text-slate-800'
            }`}
          >
            {toastType === 'success' ? (
              <CheckCircle2 className="w-4 h-4 text-[#00B365] shrink-0" />
            ) : (
              <AlertCircle className="w-4 h-4 text-[#FF6A00] shrink-0" />
            )}
            <span>{toastMessage}</span>
          </div>
        </div>
      )}
    </div>
  );
}

// src/App.vue
<template>
  <div class="min-h-screen bg-[#F2F3F5] text-slate-800 font-sans antialiased flex flex-col selection:bg-[#FF6A00] selection:text-white">
    <!-- 1. Global Header with integrated 1st-level Navigation -->
    <Header
      :activeModule="activeModule"
      :activeSubMenuId="activeSubMenuId"
      :pendingTodos="todos"
      :alerts="alerts"
      @selectModule="handleSelectModule"
      @openTodos="handleOpenTodos"
      @openAlerts="handleOpenAlerts"
      @navigateHome="handleNavigateHome"
    />

    <!-- 2. Main Workspace Area -->
    <main class="flex-1 max-w-[1600px] w-full mx-auto p-3.5 sm:p-5">
      <div v-if="activeModule === 'home'" class="space-y-3.5">
        <!-- 3.1 Platform Core Metrics Overview - Top 4 Cards -->
        <section id="workbench-metrics-overview">
          <MetricsOverview
            :metrics="metrics"
            @filterAlerts="handleFilterAlerts"
            @navigateDevelopment="activeModule = 'development'"
            @navigateScheduling="activeModule = 'scheduling'"
            @navigateQuality="activeModule = 'governance'"
          />
        </section>

        <!-- 3.2 Data Overview Statistics (数据总览统计: 数据源, 数据表, 字段, 数据量) -->
        <section id="workbench-data-overview-section">
          <DataOverviewStats
            @showToast="showToast"
            @selectDimension="handleSelectDimension"
          />
        </section>

        <!-- 3.3 Quick Shortcuts Bar -->
        <section id="workbench-shortcuts-section" class="pt-2 sm:pt-2.5">
          <QuickShortcuts
            :shortcuts="shortcuts"
            @triggerAction="handleTriggerShortcut"
            @openConfigModal="isShortcutConfigOpen = true"
          />
        </section>
      </div>

      <!-- Subsystem Dedicated Module Workspace -->
      <SubsystemModuleView
        v-else
        :module="activeModule"
        :activeSubMenuId="activeSubMenuId"
        @navigateHome="handleNavigateHome"
        @openQuickAction="handleTriggerShortcut"
        @showToast="showToast"
      />
    </main>

    <!-- 4. Global Modals -->
    <!-- 4.1 Global Search Modal (Cmd+K) -->
    <GlobalSearchModal
      :isOpen="isSearchOpen"
      @close="isSearchOpen = false"
      @selectItem="handleSearchSelectItem"
    />

    <!-- 4.2 Alert RCA Detail Modal -->
    <AlertDetailModal
      :alert="selectedAlert"
      @close="selectedAlert = null"
      @resolve="handleResolveAlert"
    />

    <!-- 4.3 Todo Approval Detail Modal -->
    <TodoDetailModal
      :todo="selectedTodo"
      @close="selectedTodo = null"
      @approve="handleApproveTodo"
      @reject="handleRejectTodo"
    />

    <!-- 4.4 Customize Shortcuts Config Modal -->
    <ShortcutConfigModal
      :isOpen="isShortcutConfigOpen"
      :shortcuts="shortcuts"
      @close="isShortcutConfigOpen = false"
      @saveShortcuts="handleSaveShortcuts"
      @resetDefault="handleResetDefaultShortcuts"
    />

    <!-- 4.5 Quick Action / SQL IDE / Sync / Perm Modal -->
    <QuickActionModal
      :actionKey="quickActionKey"
      @close="quickActionKey = null"
      @successToast="showToast"
    />

    <!-- 5. Toast Feedback -->
    <div
      v-if="toastMessage"
      class="fixed bottom-6 right-6 z-50 animate-in fade-in slide-in-from-bottom-5 duration-200"
    >
      <div
        :class="[
          'px-4 py-2.5 rounded-lg shadow-xl flex items-center gap-2.5 text-xs font-medium border bg-white',
          toastType === 'success'
            ? 'border-emerald-200 text-slate-800'
            : 'border-orange-200 text-slate-800'
        ]"
      >
        <CheckCircle2 v-if="toastType === 'success'" class="w-4 h-4 text-[#00B365] shrink-0" />
        <AlertCircle v-else class="w-4 h-4 text-[#FF6A00] shrink-0" />
        <span>{{ toastMessage }}</span>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';
import Header from './components/Header.vue';
import MetricsOverview from './components/MetricsOverview.vue';
import DataOverviewStats from './components/DataOverviewStats.vue';
import QuickShortcuts from './components/QuickShortcuts.vue';
import GlobalSearchModal from './components/GlobalSearchModal.vue';
import AlertDetailModal from './components/AlertDetailModal.vue';
import TodoDetailModal from './components/TodoDetailModal.vue';
import ShortcutConfigModal from './components/ShortcutConfigModal.vue';
import QuickActionModal from './components/QuickActionModal.vue';
import SubsystemModuleView from './components/SubsystemModuleView.vue';

import {
  PrimaryModule,
  PlatformMetrics,
  AlertItem,
  TodoItem,
  ShortcutItem,
  AlertSeverity,
} from './types';
import {
  INITIAL_METRICS,
  INITIAL_ALERTS,
  INITIAL_TODOS,
  INITIAL_SHORTCUTS,
} from './data/mockData';
import { CheckCircle2, AlertCircle } from 'lucide-vue-next';

// Navigation state
const activeModule = ref<PrimaryModule>('home');
const activeSubMenuId = ref<string | undefined>(undefined);

// Core Data States
const metrics = ref<PlatformMetrics>(INITIAL_METRICS);
const alerts = ref<AlertItem[]>(INITIAL_ALERTS);
const todos = ref<TodoItem[]>(INITIAL_TODOS);

const getInitialShortcuts = (): ShortcutItem[] => {
  try {
    const saved = localStorage.getItem('datacraft_shortcuts_v4');
    if (saved) {
      const parsed = JSON.parse(saved);
      if (Array.isArray(parsed) && parsed.length > 0) {
        return parsed.map((item: ShortcutItem) => {
          const { badge, ...rest } = item;
          return rest;
        });
      }
    }
  } catch (e) {
    console.error('Failed to load shortcuts from localStorage:', e);
  }
  return INITIAL_SHORTCUTS;
};

const shortcuts = ref<ShortcutItem[]>(getInitialShortcuts());

// Modal states
const isSearchOpen = ref(false);
const selectedAlert = ref<AlertItem | null>(null);
const selectedTodo = ref<TodoItem | null>(null);
const isShortcutConfigOpen = ref(false);
const quickActionKey = ref<string | null>(null);

// Toast Notification state
const toastMessage = ref<string | null>(null);
const toastType = ref<'success' | 'info' | 'warning'>('success');
let toastTimer: any = null;

const showToast = (msg: string, type: 'success' | 'info' | 'warning' = 'success') => {
  if (toastTimer) clearTimeout(toastTimer);
  toastMessage.value = msg;
  toastType.value = type;
  toastTimer = setTimeout(() => {
    toastMessage.value = null;
  }, 3200);
};

// Keyboard shortcut: Cmd/Ctrl + K for Global Search
const handleKeyDown = (e: KeyboardEvent) => {
  if ((e.metaKey || e.ctrlKey) && e.key === 'k') {
    e.preventDefault();
    isSearchOpen.value = !isSearchOpen.value;
  }
};

onMounted(() => {
  window.addEventListener('keydown', handleKeyDown);
});

onUnmounted(() => {
  window.removeEventListener('keydown', handleKeyDown);
  if (toastTimer) clearTimeout(toastTimer);
});

const handleSelectModule = (mod: PrimaryModule, subId?: string) => {
  activeModule.value = mod;
  activeSubMenuId.value = subId;
};

const handleNavigateHome = () => {
  activeModule.value = 'home';
  activeSubMenuId.value = undefined;
};

const handleOpenTodos = () => {
  selectedTodo.value = todos.value.find((t) => t.status === 'pending') || todos.value[0] || null;
};

const handleOpenAlerts = () => {
  selectedAlert.value = alerts.value.find((a) => a.status === 'active') || alerts.value[0] || null;
};

const handleFilterAlerts = (sev: AlertSeverity) => {
  selectedAlert.value = alerts.value.find((a) => a.severity === sev) || alerts.value[0] || null;
};

const handleSelectDimension = (key: string) => {
  if (key === 'table') {
    activeModule.value = 'metadata';
  } else if (key === 'datasource') {
    activeModule.value = 'ingestion';
  }
};

// Alert Handlers
const handleResolveAlert = (alertId: string) => {
  alerts.value = alerts.value.map((a) =>
    a.id === alertId ? { ...a, status: 'resolved' as const } : a
  );
  showToast('告警已成功处置并自动触发重跑自愈链路！');
};

// Todo Handlers
const handleApproveTodo = (id: string) => {
  todos.value = todos.value.map((t) =>
    t.id === id ? { ...t, status: 'approved' as const } : t
  );
  showToast('审批已同意通过，权限/模型变更已自动下发生效！');
};

const handleRejectTodo = (id: string) => {
  todos.value = todos.value.map((t) =>
    t.id === id ? { ...t, status: 'rejected' as const } : t
  );
  showToast('审批工单已驳回并通知申请人重新提交', 'info');
};

// Shortcut Save / Reset Handlers
const handleSaveShortcuts = (updated: ShortcutItem[]) => {
  shortcuts.value = updated;
  try {
    localStorage.setItem('datacraft_shortcuts_v4', JSON.stringify(updated));
  } catch (e) {
    console.error(e);
  }
  showToast('快捷入口配置已成功保存并实时生效！');
};

const handleResetDefaultShortcuts = () => {
  shortcuts.value = INITIAL_SHORTCUTS;
  try {
    localStorage.removeItem('datacraft_shortcuts_v4');
    localStorage.removeItem('datacraft_shortcuts_v3');
    localStorage.removeItem('datacraft_shortcuts_v2');
  } catch (e) {
    console.error(e);
  }
  showToast('已成功恢复系统预设快捷入口');
};

// Trigger Action from Shortcut - directly navigate to the corresponding secondary menu without popups
const handleTriggerShortcut = (actionKey: string, module?: PrimaryModule, subMenuId?: string) => {
  if (module && module !== 'home') {
    activeModule.value = module;
    activeSubMenuId.value = subMenuId;
    return;
  }

  if (actionKey) {
    quickActionKey.value = actionKey;
  }
};

const handleSearchSelectItem = (item: { title: string; type: string }) => {
  showToast(`已定位资产：【${item.title}】(${item.type})`);
};
</script>
